root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  pre_cmd = ["echo 'Building StackGuard...'"]
  cmd = "go build -o ./tmp/stackguard ./cmd/server"
  post_cmd = ["echo 'StackGuard Task stopped'"]
  bin = "tmp/stackguard"
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/stackguard"
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", ".git", ".vscode", ".idea"]
  include_dir = []
  include_file = []
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  log = "errors.log"
  poll = false
  poll_interval = 0
  delay = 0
  stop_on_error = false
  send_interrupt = true
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500
  args_bin = []

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true