[
  {
    "description": "AWS Access Key and Secret Key",
    "request_body": {
      "text": "My AWS credentials are: AKIAIOSFODNN7EXAMPLE and secret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY. Please keep them safe.",
      "channelId": "prod-secrets",
      "userName": "Alice"
    },
    "expected_detections": ["AWS Access Key", "AWS Secret Key"]
  },
  {
    "description": "GitHub Personal Access Token (PAT)",
    "request_body": {
      "text": "Got a new GitHub token: ghp_abcdefghijklmnopqrstuvwxyz0123456789. Don't commit this!",
      "channelId": "dev-ops",
      "userName": "Bob"
    },
    "expected_detections": ["GitHub Token"]
  },
  {
    "description": "JWT Token",
    "request_body": {
      "text": "Here's the latest JWT for testing: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
      "channelId": "api-access",
      "userName": "Charlie"
    },
    "expected_detections": ["JWT Token"]
  },
  {
    "description": "Database URL (MongoDB)",
    "request_body": {
      "text": "Connection string for MongoDB: mongodb://admin:securepassword@prod-db.example.com:27017/myapp?authSource=admin",
      "channelId": "database-team",
      "userName": "David"
    },
    "expected_detections": ["Database URL"]
  },
  {
    "description": "Private Key (Partial PEM header)",
    "request_body": {
      "text": "Found a key here: -----BEGIN RSA PRIVATE KEY-----\nMIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJgAgEAAoGBAM2rW...\n-----END RSA PRIVATE KEY-----",
      "channelId": "security-incident",
      "userName": "Eve"
    },
    "expected_detections": ["Private Key"]
  },
  {
    "description": "Slack API Token",
    "request_body": {
      "text": "My new bot token is xoxb-123456789012-ABCDEFGHIJKLMNOPQRSTUVWXYZAB for testing.",
      "channelId": "integrations",
      "userName": "Frank"
    },
    "expected_detections": ["Slack Token"]
  },
  {
    "description": "Google API Key",
    "request_body": {
      "text": "Check this Google API key: AIzaSyB_1234567890abcdefghijklmnopqrstuvwx",
      "channelId": "frontend-dev",
      "userName": "Grace"
    },
    "expected_detections": ["Google API Key"]
  },
  {
    "description": "Generic API Key",
    "request_body": {
      "text": "This is a new service_api_key: v3rYS3cur34p1K3Yw!thR@nd0mCh@rs",
      "channelId": "new-service",
      "userName": "Heidi"
    },
    "expected_detections": ["API Key Generic"]
  },
  {
    "description": "Very long message with a GitHub token at the end (over 5000 chars)",
    "request_body": {
      "text": "This is a very long message designed to test the `text` field handling for inputs exceeding 5000 characters. It will contain repetitive filler text, which would typically be ignored, but the secret itself should be detected regardless of its position within this extensive content. The purpose is to ensure that the scanner can efficiently process large messages and correctly identify embedded secrets without being overwhelmed or missing critical information due to length limitations. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Final important detail: The new GitHub token is ghp_finaltokenatendoflongmessage12345.",
      "channelId": "data-dump",
      "userName": "BigDataGuy"
    },
    "expected_detections": ["GitHub Token"]
  }
]
